### ISSUE TITLE
Facet and refine search results by repository

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#12]
Search results should facetable by repository.

**Acceptance criteria**

* Clicking a specific facet value in the "Repository" facet limits results to collections/components matching that facet value.

- - - 
* Ref: req 1.9
* Category: 1. Core Discovery
* Subcategory: Browse

**Comment by drh-stanford** [comment]
Relies on a `solr_ead` code change here https://github.com/awead/solr_ead/pull/10

**Comment by drh-stanford** [comment]
In reading over the EAD 2002 docs, it's not clear to me how exactly to extract the repository -- see http://eadiva.com/2/repository/. What is the common practice?

As I read the spec, `archdesc/did/repository/text()` works, but also they mention `archdesc/did/respository/corpname/text()` and `archdesc/did/repository/name/text()` and `archdesc/did/repository/address/addressline/text()`, among others.

Thus far, I've been assuming that `archdesc/did/repository` works because it'll only have a single subelement or just text. e.g.,

```xml
<repository>My Repository</respository>
```
or, like our fixture data:

```xml
<repository><corpname>My Repository</corename></repository>
```

Are these two examples sufficient for our MVP?

**Comment by anarchivist** [comment]
For the facet itself, I think we should be explicitly checking for `//archdesc/did/repository/corpname` or `//archdesc/did/repository/name` only. The repository information that would appear in the sidebar mockups (see #145) would pull from everything in the `<repository/>` element, or data sourced elsewhere (e.g. a YAML file or a Repository object backed by a model).
