### ISSUE TITLE
Add scrollspy behavior to sidebar on collection show page

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/arclight#178]
Broken out of #144

- [ ] The navigation aid should also exhibit "scrollspy" behavior, highlighting the currently active section.

![collection-detail-overview-no-inventory-markedup](https://cloud.githubusercontent.com/assets/73732/25079071/fbaf007e-22ed-11e7-95a5-698d6d9ea7cf.jpg)

**Comment by mejackreed** [comment]
A question for @ggeisler here. Should the main content body be the only part that is scrollable? (right side of page in mock)

**Comment by ggeisler** [comment]
@mejackreed  Yes, I think the idea is that the main content on the right is the only part that scrolls. Scrollspy is relevant,  I believe, in that if the main content area is longer than in the mockup and you scroll up so that either the Access and Use or Indexed Terms heading is the top-most heading, the highlighted heading in the sidebar changes to correspond.

Not sure if that matches your assumption or not.

Also, we might have to use the implementation a bit to confirm that it feels like the best interaction for the page. Hard to be 100% sure with static mockups.
