### ISSUE TITLE
Display an embedded viewer on the collection detail page

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#277]
Subtask of #242

**Comment by ggeisler** [comment]
Here's a shot at this, though I'd certainly welcome feedback and other ideas (@jvine).

If a collection has digital objects at the collection-level (this is determined by looking at the collection object in the repository, not the finding aid, I assume?), we show a third tab, called "Digital content" (unless there are better ideas for the label).

For the Digital content page, we simply show the appropriate viewer with the collection-level digital objects. I'm not sure that any other information needs to be on this page, given the collection is otherwise fully described in the Overview and Contents tabs.

For this mockup, the real-life example of a collection with collection-level digital items is:

* Finding aid: http://www.oac.cdlib.org/findaid/ark:/13030/c81v5kjj/
* Catalog record: https://searchworks.stanford.edu/view/9704519

![arclight-mockups-end-user-ui__collection_-_digital_content](https://cloud.githubusercontent.com/assets/101482/26011804/5485d0ba-3707-11e7-963b-f764e5790e59.png)

**Comment by ggeisler** [comment]
Discussed with @jvine and will be making some updates to the mockup above.

**Comment by ggeisler** [comment]
Updates below. We think it would be helpful to have two versions of a new "Online content" tab for the Collection Detail page:

- Show viewer when there is collection-level online content attached to the collection
- Show a results list when there is component-level online content in the collection

### Collection-level online content
![viewer](https://cloud.githubusercontent.com/assets/101482/26180086/21176fa4-3b1c-11e7-9aa8-e5071db09c6f.png)

###  Component-level online content
![all-online-content](https://cloud.githubusercontent.com/assets/101482/26180091/2d73b488-3b1c-11e7-851c-929e68d2c344.png)

**Comment by anarchivist** [comment]
I quite like this pattern, @ggeisler. A few questions:

* How does relate to or replace the "Online" section of the accordion sidebar? 
* What happens if there is more than one digital object associated at the collection-level?

**Comment by ggeisler** [comment]
@anarchivist 

> How does relate to or replace the "Online" section of the accordion sidebar?

As you might realize, this new tab is only relevant to the Collection Detail page, not a regular component detail page, and I'm unsure about what we're planning for the "Online" section of the Collection sidebar so am not sure how to answer this. The only collection we currently show an "Online" section for is the Alpha Omega collection and I'm not sure what the history slideshow there is. Is it digital items attached at the collection-level?

> What happens if there is more than one digital object associated at the collection-level?

Wouldn't the viewer accommodate that? In the example, the assumption is there are 216 objects associated at the collection-level. Each one is listed in the sidebar of the viewer. Would that not work? Maybe I don't understand well enough how the digital objects will be handled and passed to the viewer when they are collection-level, rather than component-level?

**Comment by jvine** [comment]
> How does relate to or replace the "Online" section of the accordion sidebar?

Hm. On the component detail page, the 'Online' section is meant to exist when there is no embeddable viewer, and contain links to external viewers/sites. So what happens on the collection detail page if there is online content, but no embeddable viewer...? I don't think the sidebar section will work here (and am open to argument that it doesn't work in the component detail page, either...)

> What happens if there is more than one digital object associated at the collection-level?

I thought the same as Gary - viewer would handle multiple objects.

**Comment by anarchivist** [comment]
@ggeisler 💬 

> As you might realize, this new tab is only relevant to the Collection Detail page, not a regular component detail page, and I'm unsure about what we're planning for the "Online" section of the Collection sidebar so am not sure how to answer this. The only collection we currently show an "Online" section for is the Alpha Omega collection and I'm not sure what the history slideshow there is. Is it digital items attached at the collection-level?

@jvine 💬 

> Hm. On the component detail page, the 'Online' section is meant to exist when there is no embeddable viewer, and contain links to external viewers/sites. So what happens on the collection detail page if there is online content, but no embeddable viewer...? I don't think the sidebar section will work here (and am open to argument that it doesn't work in the component detail page, either...)

Currently the "Online" section of the sidebar (in both the collection and component views) displays one button for each `<dao/>` only at the given label in the following ways:

* For a collection detail view, display one button for each `<dao/>` that is an immediate child element of the collection-level `<archdesc/>` information:

![screen shot 2017-05-18 at 5 18 54 pm](https://cloud.githubusercontent.com/assets/73732/26228444/b6b9dff6-3bee-11e7-9238-1e3c225f790f.png)

* For a component detail view, display one button for each `<dao/>` that is an immediate child element of that component:

![screen shot 2017-05-18 at 5 22 22 pm](https://cloud.githubusercontent.com/assets/73732/26228453/bf522470-3bee-11e7-9b6f-ce26e395fe25.png)

Per @jvine, I'm not totally sure if this works either. While it might be an antipattern to have multiple `<dao/>`s attached here I think it's not out of the question in terms of dealing with real data. 

@ggeisler 💬 

> > What happens if there is more than one digital object associated at the collection-level?
>
> Wouldn't the viewer accommodate that? In the example, the assumption is there are 216 objects associated at the collection-level. Each one is listed in the sidebar of the viewer. Would that not work? Maybe I don't understand well enough how the digital objects will be handled and passed to the viewer when they are collection-level, rather than component-level?

It wouldn't work (at this point) because presumably the viewer would need to know how to aggregate those objects into display. It would necessarily require that the collection-level object would link out to some aggregate object. However, this could be something that we choose to punt on for now, or acknowledge that there's further work to do.

**Comment by ggeisler** [comment]
@anarchivist: @jvine and I discussed this more today. We understand that the collection-level view where all objects attached at the collection-level are shown in a single viewer isn't feasible to work as mocked-up above but we still like the idea of the new, third "Online Content" tab. Could we just follow the patten of the "Component-level online content" mockup and use that for the collection-level case as well?

**Comment by anarchivist** [comment]
Yep, this that sounds good. Thanks @ggeisler and @jvine!
