### ISSUE TITLE
Individual repositories should have their own route(s)

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#329]
**Acceptance criteria**

* Each configured repository should have an easy to remember route based on its slug/ID to the faceted search results for that repository
    * for example `/repositories/hoover` should show me the same content as <br/> `/catalog?f%5Brepository_sim%5D%5B%5D=Hoover+Institution+Archives`
* Each repository linked from the repositories page (`/repositories`) should be linked to its corresponding slug

**Comment by drh-stanford** [comment]
One concern is that from page 4 of the mockups, it looks like the idea is to have a single page view of the repository's collections. The problem is that if they have, say, 100 collections, then the default Blacklight search results will require paging, and then blacklight will replace that vanity URL when they go to the next page. I can disable paging by putting in a high per-page value.

**Comment by drh-stanford** [comment]
Also, should the repository detail page only show the collections? I'm assuming so based on page 4 of the mockups.

**Comment by ggeisler** [comment]
@drh-stanford When you refer to page 4 of the mockups, you're referring to the End-User_UI mockups, not the MVP mockups, correct? If so, note that this page in not intended to show all of the repository's collections (see note 1 on the mockup page), so I don't think paging needs to be an issue there.

@anarchivist can correct me but at this point I'd assume that, yes, only collections (along with repository card at the top) on this page for now.

**Comment by anarchivist** [comment]
This is correct. I'd also add that ultimately the repositories page is also a placeholder for some additional functionality that's out of scope for the MVP.

**Comment by drh-stanford** [comment]
I've tried to implement the persistent vanity url without much luck. @mejackreed suggested that @jkeck might have some insight into the problem I'm running into. I'm overriding the CatalogController's `index` method so that I can add the repository name to the facet query, but it doesn't work. Notice on the screenshot that it thinks it's faceting on the repository name (see the "search context" and the facet highlight) but the query didn't actually get done.

![screen shot 2017-05-22 at 12 46 48 pm](https://cloud.githubusercontent.com/assets/1861171/26325695/d0d870b8-3eec-11e7-9bf3-0282b74502c0.png)
![screen shot 2017-05-22 at 12 46 05 pm](https://cloud.githubusercontent.com/assets/1861171/26325697/d2e9b43e-3eec-11e7-95c5-2d9e59b2a927.png)

So, I discussed this with @mejackreed a bit and rather than getting bogged down in Blacklight stuff, maybe the best approach is to just display the collections rather than a full faceted search results page. That is more straightforward implementation-wise, and more inline with the mockups. @anarchivist what do you think about that approach instead of doing "the faceted search results for that repository".

**Comment by drh-stanford** [comment]
Here's an example of what a simple repository detail view would look like:

![screen shot 2017-05-22 at 2 17 09 pm](https://cloud.githubusercontent.com/assets/1861171/26329606/dcec41e4-3efc-11e7-94ce-4ac49e6612d5.png)

**Comment by ggeisler** [comment]
Looks good.

**Comment by drh-stanford** [comment]
Discussed in standup and this looks good to go.
