### ISSUE TITLE
Index some more notes

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#346]
**Acceptance criteria**

* Index the following notes at the collection and component level:
    * Children of `//archdesc` or a component:
        * `<accruals/>`
        * `<bibliography/>`
        * `<fileplan/>`
        * `<note/>`
        * `<odd/>`
        * `<phystech/>`
   * Children of `//archdesc/did` or a component's `<did/>`:
        * `<materialspec/>`
        * `<note/>`
        * `<physloc/>`

Related to #347

**Comment by drh-stanford** [comment]
the current indexing code only extracts the `<p/>` text from these "note" elements. it seems to be doing this because it's assuming that the markup within the note contains `<head/>` and `<p/>` elements and it breaks them out. this is what our fixture data looks like -- https://github.com/sul-dlss/arclight/blob/master/spec/fixtures/ead/nlm/alphaomegaalpha.xml#L108-L136 for example.

@anarchivist is this sufficient, and a best practice? 

or do we need to handle the other types of markup in the element as described by the loc spec -- for example, `<odd/>` can contain a `<list/>`, `<blockquote/>`, etc. and their example doesn't use `<p/>` or `<head/>` -- http://www.loc.gov/ead/tglib/elements/odd.html

**Comment by anarchivist** [comment]
@drh-stanford 💬 

> @anarchivist is this sufficient, and a best practice?

For the most part.

> do we need to handle the other types of markup in the element as described by the loc spec -- for example, `<odd/>` can contain a `<list/>`, `<blockquote/>`, etc. and their example doesn't use `<p/>` or `<head/>` -- http://www.loc.gov/ead/tglib/elements/odd.html

We probably should, at least in terms of grabbing text. How do you think we should break that out in this ticket?

**Comment by drh-stanford** [comment]
If the text is within a `<p/>` tag, like this: `<p><list><item>...</item></list></p>` then we'll extract all of the text. The problem is when there's not a `<p/>` element, as in their example. 

Here's one in our fixtures:

```
    <odd id="aspace_3be3b2c4bb6ad119fb3027aa9f75fb91">
      <head>General</head>
      <list type="ordered">
        <head>Contact Information</head>
        <item>History of Medicine Division</item>
        <item>National Library of Medicine</item>
        <item>8600 Rockville Pike</item>
        <item>Bethesda, Maryland</item>
        <item>USA</item>
        <item>Phone:(301) 402-8878 (Reference Desk)</item>
        <item>Fax:(301) 402-0872</item>
        <item>Email:hmdref@nlm.nih.gov</item>
      </list>
    </odd>
```
