### ISSUE TITLE
Update "All fields" search for fielded search

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#347]
Broken out of #334. We should update the "All Fields" search handler.

**Acceptance criteria**

* Add the following fields to the "all fields" search handler:
    * Existing fielded searches
         * `title_ssm`
         * `places_ssm`
         * `names_ssim`
         * `access_subjects_ssim`
         * `scopecontent_ssm`
    * Notes fields (see also #346)
         * `abstract_ssm`
         * `accessrestricct_ssm`
         * `acqinfo_ssm`
         * `altformavail_ssm`
         * `appraisal_ssm`
         * `arrangement_ssm`
         * `bioghist_ssm`
         * `custodhist_ssm`
         * `originalsloc_ssm`
         * `physdesc_ssm`
         * `processinfo_ssm`
         * `relatedmaterial_ssm`
         * `scopecontent_ssm`
         * `separatedmaterial_ssm`
         * `userestrict_ssm`
    * Additional structured fields
        * `unitid_ssm`

**Comment by drh-stanford** [comment]
Just some notes on the implementation here... Our `solr_ead`-based indexer currently works by using all `:searchable` fields for the "All fields" search. See https://github.com/awead/solr_ead/blob/master/lib/solr_ead/document.rb#L34-L67 for an example of the ones that `solr_ead` marks as `:searchable` at the collection-level. There's likely too many fields marked searchable and that based on the above criteria we'd rather have a specific list of fields/notes that should be searched that does not depend on the complexities of `solr_ead`. So, my strategy is to use a `copyField` list that is specific to the fields that we want searched in the `text` field, rather than copying every `:searchable` field. See https://github.com/sul-dlss/arclight/blob/master/solr/conf/schema.xml#L556-L557
