### ISSUE TITLE
Incorrect heading styling on component show page hierarchy display

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#380]
The work on #363 needs to be applied consistently to the hierarchy display on the component show page. See screenshots below.

~This probably should be addressed while working on #374.~ (see @ggeisler's comment)

**Collection show page screenshot** 

![screen shot 2017-05-24 at 9 49 50 am](https://cloud.githubusercontent.com/assets/73732/26415254/b6664e78-4066-11e7-81d4-4d992a444e9f.png)

**Component show page screenshot** 

![screen shot 2017-05-24 at 9 51 38 am](https://cloud.githubusercontent.com/assets/73732/26415238/a7812c8e-4066-11e7-8516-36783231d2bd.png)

**Comment by ggeisler** [comment]
I haven't worked on styling the component detail page yet, but plan to. I'd suggest I work on the styling issues noted in this ticket, rather than that being done by the person who picks up #374 because although they deal with the same page, the styling work is completely independent of the work required for #374, and I'm already familiar with the patterns used for the styling.

**Comment by drh-stanford** [comment]
The component show page has a slightly different class structure. The `.al-hierarchy-level-N` wasn't working within the `.blacklight-series` parent for the component page. On the component page, the parent is whatever that component's type is `.blacklight-file`, for example. So this line seems to be preventing the matches on the Component page -- https://github.com/sul-dlss/arclight/blob/master/app/assets/stylesheets/arclight/modules/hierarchy.scss#L52
