### ISSUE TITLE
Review "Technical solution" slide in inception deck

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#441]
See slide 10. I updated this based on my understanding of the architecture currently.

https://docs.google.com/presentation/d/1dusFIz-qNaZBtdzzio7a6pxP8lGlC0F9vxAKicsZ-uI/edit

**Comment by jkeck** [comment]
The only (very minor) quibble I would have with this is that the boxes labeled `ArcLight` and `ArcLight webapp` should be swapped.

The ArcLight webapp is what is deployed to AWS and it has all of the components listed installed into it.

It looks good to me otherwise.  I'll leave this open for others to comment.  I'm particularly interested in hearing @camillevilla's opinion given her relative newness to the stack.

**Comment by anarchivist** [comment]
Thanks, @jkeck. I think that change would be fine - my intention was to reflect that the codebase unified the webapp and indexing code, but the indexing was in some senses "separate" (at least from a user perspective, because we don't surface anything related to indexing in the UI yet).

**Comment by anarchivist** [comment]
I've updated the diagram to include an oEmbed provider and Google Forms (since they provide the demonstration implementations for object viewers and request forms).
