### ISSUE TITLE
Collection contents view: make components bookmarkable

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#443]
**Acceptance criteria**

When viewing a collection's contents tab:

* Any components that display should be bookmarkable
* Adding them as a bookmark should show them on the "Bookmarks" page

**Comment by drh-stanford** [comment]
I've looked into this a bit and the default behavior for the bookmark control looks like this:

![screen shot 2017-06-02 at 9 52 33 am](https://cloud.githubusercontent.com/assets/1861171/26736031/4ce30058-4779-11e7-93dc-50b9286e6351.png)

but there's a problem because clicking on the bookmark button causes the page to refresh and thus you lose your place in the Contents tab. So, the task at hand is to do that request asynchronously.

**Comment by anarchivist** [comment]
Is the checkbox that we're using (e.g. in search results) feasible here?

**Comment by drh-stanford** [comment]
Yes, I was able to make that work...

![screen shot 2017-06-02 at 11 11 29 am](https://cloud.githubusercontent.com/assets/1861171/26738769/472ce592-4784-11e7-8d4e-10be926d9298.png)

**Comment by drh-stanford** [comment]
@anarchivist should we also show the bookmark control in the collection context?

![screen shot 2017-06-02 at 11 56 21 am](https://cloud.githubusercontent.com/assets/1861171/26740491/a49164dc-478a-11e7-9822-4958fd4bc9b1.png)

**Comment by anarchivist** [comment]
I thnnk we should keep it out of the context display for now.
