### ISSUE TITLE
Figure out indexing blockers on demo machine

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#444]
@jkeck and @eefahy to pair on this.

**Comment by jkeck** [comment]
This was caused by the indexing job timing out due to the additional EADs.  Currently, our indexing is done with a `container_command` .in an `ebexenstions` file.

We've currently solved this by upping the timeout, as you can see in our `seed.config` file: https://github.com/sul-dlss/arclight-demo/blob/master/.ebextensions/seed.config

This will eventually timeout again if we add enough EADs to cause the indexing job to take longer than 1 hour.

This indicates that we may want to move to a different indexing strategy eventually.  This will take some more thought and consideration wrt how we trigger indexing to happen that is not tied directly to the deployment task (e.g. cron), but we will have to cross that bridge once we get there.
