### ISSUE TITLE
Review and evaluate existing code bases for potential reuse

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#91]
*EAD indexing code*

* [x] solr_ead: https://github.com/awead/solr_ead 
* [x] NYU’s ead_indexer (uses solr_ead): https://github.com/NYULibraries/ead_indexer  

*Existing Blacklight applications*

* [x] NYU Finding Aids application: https://github.com/NYULibraries/findingaids (implementation: https://specialcollections.library.nyu.edu/search/) 
    * Context: forked by Columbia to do some local prototyping (implementation: https://fabl-dev.cul.columbia.edu/)
* [x] Fable (fork of NYU code): https://github.com/blacklight-fable/fable
    * Context: intended as starting point to extract engine from existing application

**Comment by drh-stanford** [comment]
`solr_ead` is a gem with a latest release of Aug 2014. It's written with OM and it indexes EAD into Documents with multiple Components. See https://github.com/awead/solr_ead/blob/master/lib/solr_ead/document.rb and https://github.com/awead/solr_ead/blob/master/lib/solr_ead/component.rb.

When creating a solr document, it extracts the `SolrEad::Document` fields and creates a Solr record for it, and then for each component (e.g., `<c>...</c>`) it adds them as distinct Solr records. See https://github.com/awead/solr_ead/blob/master/lib/solr_ead/indexer.rb#L48-L52. There's a parent/child structure embedded within the flattened solr fields -- see https://github.com/awead/solr_ead/blob/master/lib/solr_ead/behaviors.rb#L68-L75

The gem has a full test suite and EAD fixtures. See https://github.com/awead/solr_ead/tree/master/spec/fixtures

**Comment by drh-stanford** [comment]
@mejackreed and I reviewed `solr_ead` and we think the gem itself is a good starting point for quickly getting the indexing going. We may find that it doesn't meet our requirements re: hierarchy but it's unclear to us right now what those are. The OM usage is pretty straight-forward and we could extract it out if needed to build our own gem for some future reason (it basically maps XPath expressions into Solr fields).

We'd likely need to fork the repo if we did want to make changes to the gem, as it's been inactive since 2014, so that's a risk factor.

The NYU ead_indexer is also straight-forward indexing tasks. We recommend writing our own indexing rake tasks that we'd put and maintain in this repo here.

**Comment by jkeck** [comment]
Sounds good.  Also, I think we should talk with the maintainer (who we know well) about the future of that gem.

**Comment by drh-stanford** [comment]
The NYU Finding Aids application is a generated blacklight application with local modifications.  It doesn't have generators, just local mods, for example. I think we can scavenge code from the repo, but it's not going to be useable as-is technically. One example is some of the solr configuration like this -- https://github.com/NYULibraries/findingaids/blob/master/lib/findingaids/solr/catalog_helpers.rb

**Comment by drh-stanford** [comment]
Perhaps we want to discuss these points before closing the ticket?

**Comment by anarchivist** [comment]
I'm not sure we need any further discussion, but let's check in on Monday - most of these things we've at least talked about in passing.
